### ISSUE TITLE
在pages.config.ts配置easycom无效

### ISSUE THREAD

**Issue by tanwenchao** [uni-helper/vite-plugin-uni-pages#101]
### 描述问题

<img width="692" alt="image" src="https://github.com/uni-helper/vitesse-uni-app/assets/17673324/90d0e40a-7617-422a-bb6b-367406c4debe">

### 复现

在pages.config.ts配置easycom无效

### 系统信息

```Shell
在pages.config.ts配置easycom无效
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
#78

**Comment by KeJunMao** [comment]
检查生成的 pages.json

**Comment by tanwenchao** [comment]
在pages.config.ts配置easycom无效，在Pages.config.ts中配置后，生成的pages.json没有


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "uni-helper/vite-plugin-uni-pages"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月14日(星期一) 下午5:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [uni-helper/vite-plugin-uni-pages] 在pages.config.ts配置easycom无效 (Issue #101)





 
检查生成的 pages.json

**Comment by KeJunMao** [comment]
![image](https://github.com/uni-helper/vite-plugin-uni-pages/assets/18414281/d072c30f-876d-4695-ac13-ec638ca0c510)
无法复现
