### ISSUE TITLE
volar route配置无效

### ISSUE THREAD

**Issue by tanwenchao** [uni-helper/vite-plugin-uni-pages#103]
### 描述问题

![image](https://github.com/uni-helper/vite-plugin-uni-pages/assets/17673324/6ed04e25-54ff-470c-9772-fcc6544377a7)
在pages根目录新建index.vue配置<route>是可以的，
<img width="1125" alt="image" src="https://github.com/uni-helper/vite-plugin-uni-pages/assets/17673324/80095475-23f1-4706-a6f8-964f8c2c3830">

### 复现

在pages新建其他目录有问题，比如我在这里新建了个my的文件夹，在my文件夹下面放index.vue，此时配置的route信息就不能生效了
<img width="1422" alt="image" src="https://github.com/uni-helper/vite-plugin-uni-pages/assets/17673324/1fbd4634-8ed8-43fe-aa24-43ca5766f75c">

<img width="1445" alt="image" src="https://github.com/uni-helper/vite-plugin-uni-pages/assets/17673324/f9c69408-f5b8-4658-8033-96edb042e41e">

### 系统信息

```Shell
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 35.23 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 17.4.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    pnpm: 8.3.1 - /usr/local/bin/pnpm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 14.1.2

"@uni-helper/volar-service-uni-pages": "^0.2.6"
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
看你的截图没问题呀

**Comment by KeJunMao** [comment]
![demo](https://github.com/uni-helper/vite-plugin-uni-pages/assets/18414281/d51ed95c-6c37-4489-8169-947161bcf7d1)

未能复现，请提供一个最小仓库~

**Comment by tanwenchao** [comment]
骚瑞，我的问题，在pages.config.ts中定义了pages
