### ISSUE TITLE
支持类型安全

### ISSUE THREAD

**Issue by ModyQyW** [uni-helper/vite-plugin-uni-pages#105]
### 对问题的清晰和简明的描述

[unplugin-vue-router](https://github.com/posva/unplugin-vue-router) 是一个实验性的库，支持约定式路由、类型安全等，周下载量有 157k，前景非常好。

目前，vite-plugin-uni-pages 已经支持了约定式路由。我在想，我们是不是可以尝试支持类型安全，与 unplugin-vue-router 做功能对标？这同时也会带来更好的 DX。

### 推荐的解决方案

生成 .d.ts，覆写 uni-app 提供的类型。

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by KeJunMao** [comment]
对 uni 的 router 相关函数做吗

**Comment by ModyQyW** [comment]
是的，但这只是初步想法，不确定可不可行
