### ISSUE TITLE
升级最新版0.2.7后pages.config.js中配置globalStyle tabBar都不生效了

### ISSUE THREAD

**Issue by LetFree** [uni-helper/vite-plugin-uni-pages#107]
### 描述问题

生成的pages.json中无globalStyle、tabBar信息

### 复现

无

### 系统信息

```Shell
无
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
try 0.2.8
