### ISSUE TITLE
pages.config.ts 中 pages 丢失最高优先级

### ISSUE THREAD

**Issue by ModyQyW** [uni-helper/vite-plugin-uni-pages#112]
### 描述问题

pages.config.ts 中 pages 丢失最高优先级

### 复现

```shell
# clone
git clone git@github.com:uni-helper/vite-plugin-uni-pages.git
cd vite-plugin-uni-pages
# 修改文件名
mv packages/playground/src/pages/index.vue packages/playground/src/pages/home.vue
```

之后注释 `vite.config.ts` L17

<img width="552" alt="image" src="https://github.com/uni-helper/vite-plugin-uni-pages/assets/31850793/add0698f-ccb1-4034-9ae0-a859252a6c6e">

修改 `pages.config.ts` L12

<img width="517" alt="image" src="https://github.com/uni-helper/vite-plugin-uni-pages/assets/31850793/bdb40bec-4172-4d24-b72d-bce078f29dd7">

```shell
# 运行
pnpm run play:mp-weixin
```

检查生成的 `pages.json`，和配置不一致。应该只生成 `pages/home` 相关部分。

<img width="402" alt="image" src="https://github.com/uni-helper/vite-plugin-uni-pages/assets/31850793/26b2e407-2dc6-44fa-83af-ff3c429c4aff">

### 系统信息

```Shell
➜  ~/Documents/uni-helper/vite-plugin-uni-pages git:(main) ✗ npx envinfo --system --binaries --browsers

  System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M2 Pro
    Memory: 64.30 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/Library/Caches/fnm_multishells/53363_1696734555007/bin/node
    npm: 9.5.1 - ~/Library/Caches/fnm_multishells/53363_1696734555007/bin/npm
    pnpm: 8.7.6 - ~/Library/Caches/fnm_multishells/53363_1696734555007/bin/pnpm
    Watchman: 2023.10.02.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 117.0.5938.149
    Safari: 17.0

➜  ~/Documents/uni-helper/vite-plugin-uni-pages git:(main) ✗
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
只生成 pages/home 的话需要禁用自动发现

**Comment by KeJunMao** [comment]
什么情况下需要手动指定 pages 呢？

**Comment by ModyQyW** [comment]
我个人看到最高优先级的表述时，潜意识认为只要定义了 `pages` 就会覆盖自动扫描得出的页面。

> 其实就是合并行为该怎么处理，有什么好的方案吗，每个人都有自己的心理预期合并行为

我不太确定。我目前的想法可能是扩展 `mergePages` 这个选项，甚至可能是改动这个选项的名字，允许定义不同的合并行为，也可以直接使用预设的合并行为。这个值得做吗？

> 什么情况下需要手动指定 pages 呢？

某些老旧小程序可能使用了非 index 作为首页，这种情况下就会有所需求。我觉得这方面在文档里说明就好了？

都是些想法，全靠大哥定夺🙏

**Comment by KeJunMao** [comment]
非 index 目前可以使用 route-block 的 type 指定，或者插件的homePage选项设置吧？

**Comment by KeJunMao** [comment]
合并结果其实可以在目前提供的几个 hook 里修改

**Comment by ModyQyW** [comment]
> 非 index 目前可以使用 route-block 的 type 指定，或者插件的homePage选项设置吧？

你说的对，可能这样会更简单一点，不用纠结太多。
