### ISSUE TITLE
自动检测 vite-plugin-uni-platform 插件是否存在，存在时自动启用过滤器

### ISSUE THREAD

**Issue by KeJunMao** [uni-helper/vite-plugin-uni-pages#113]
### 对问题的清晰和简明的描述

自动检测 vite-plugin-uni-platform 插件是否存在，存在时自动启用过滤器，进一步降低 vite-plugin-uni-platform 插件使用成本

### 推荐的解决方案

从 vite config 中获取插件列表，从而判断并启用

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by ModyQyW** [comment]
🐮
