### ISSUE TITLE
page.config.js配置的pages import的其他js的export，修改了export的内容不能同步更新

### ISSUE THREAD

**Issue by mistery-li** [uni-helper/vite-plugin-uni-pages#115]
### 描述问题

![image](https://github.com/uni-helper/vite-plugin-uni-pages/assets/19723639/78014584-d2c9-4657-a960-e58ed6e3bd43)

如图所示，修改了该文件的pages配置，并不会自动更新到pages.json

### 复现

![image](https://github.com/uni-helper/vite-plugin-uni-pages/assets/19723639/b441b842-4ae3-4c00-9090-727c223eace5)

### 系统信息

```Shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 87.61 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.0 - /opt/homebrew/bin/npm
    pnpm: 8.6.5 - /opt/homebrew/bin/pnpm
    Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 117.0.5938.149
    Safari: 16.5.2
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
项目底层使用 c12 来 watch 配置文件，c12 不支持监听导入的模块

**Comment by mistery-li** [comment]
> 项目底层使用 c12 来 watch 配置文件，c12 不支持监听导入的模块

我看了issue有个类似的配置参数configSource之类的监听，是否可以考虑支持增加配置watch某个目录？目前只能改了文件再去pages.config.js保存一次

**Comment by zguolee** [comment]
> > 项目底层使用 c12 来 watch 配置文件，c12 不支持监听导入的模块
> 
> 我看了issue有个类似的配置参数configSource之类的监听，是否可以考虑支持增加配置watch某个目录？目前只能改了文件再去pages.config.js保存一次

我们可能不会考虑支持watch某个目录，有一些vite插件已经提供了这个功能。[see more](https://github.com/search?q=vite%20plugin%20reload&type=repositories)

**Comment by KeJunMao** [comment]
是的，应该短期内不会去支持，就算支持也不是新增配置项，而是读取配置的源代码并将其转为ast提取import来将其add到watch
