### ISSUE TITLE
`subPackages` 文件夹中的 `vue` 文件，变更 `<route>` 中的属性值时，热更新后，`app` 页面未更改

### ISSUE THREAD

**Issue by lx11573** [uni-helper/vite-plugin-uni-pages#118]
### 描述问题

在 `subPackages` 文件夹中的 `vue` 文件，更改  `<route>`  中的属性时，热更新后，`app` 页面未更新
而在  `dir` 中的 `vue` 文件则没有这个问题
同时，如果更改了 `subPackages` 中文件的 `<route>`  的属性时后，如果继续更改 `dir` 中的文件，热更新后，页面会更新

### 复现

无

### 系统信息

```Shell
System:
  OS: macOS 12.7.1
Binaries:
  Node: 16.17.0
  npm: 10.2.5
  pnpm: 8.11.0
Browsers:
  Chrome: 120.0.6099.71
Volar:  1.8.25
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
谢谢反馈，晚点我看看~
