### ISSUE TITLE
`easycom` 的 `autoscan` 属性类型需要修改为可选

### ISSUE THREAD

**Issue by sunpm** [uni-helper/vite-plugin-uni-pages#120]
### 描述问题

https://uniapp.dcloud.net.cn/collocation/pages#easycom

### 复现

https://uniapp.dcloud.net.cn/collocation/pages#easycom

### 系统信息

```Shell
https://uniapp.dcloud.net.cn/collocation/pages#easycom
```

### 使用的包管理器

yarn

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
https://github.com/uni-helper/vite-plugin-uni-pages/blob/738d570631b8f2e01cf2fd26fd7e136f76e24787/packages/core/src/config/types/index.ts#L119

应该是有的

**Comment by sunpm** [comment]
抱歉，是我看错报错信息了，应该是 `autoscan` 属性可选
<img width="1078" alt="image" src="https://github.com/uni-helper/vite-plugin-uni-pages/assets/35005831/6bbd0bb5-89e3-4b1f-8ff7-9164c66bc3bb">
