### ISSUE TITLE
pages.config.js中条件编译生成page.json自动去除了

### ISSUE THREAD

**Issue by webzhouyan** [uni-helper/vite-plugin-uni-pages#122]
### 描述问题

`       // #ifndef APP-PLUS
        'navigationStyle': 'custom',
        // #endif
`
生成的pages.json被自动去除了

### 复现

`       // #ifndef APP-PLUS
        'navigationStyle': 'custom',
        // #endif
`

### 系统信息

```Shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 96.80 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.6.7 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 17.2.1
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [x] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
您好，没能看懂您要表达什么

**Comment by webzhouyan** [comment]
> 您好，没能看懂您要表达什么
我在pages.config.js中写的不同平台条件编译的注释代码如上，运行之后生成的page.json中不含有相关代码如  // #ifndef APP-PLUS   // #endif，条件编译的相关注释代码并没有在page.json生成

**Comment by KeJunMao** [comment]
都用js了，其实可以直接使用if else呢

**Comment by KeJunMao** [comment]
@zguolee pages.config.ts 是不能用条件编译的吧？为啥之前你在readme中写了呢？

**Comment by codercup** [comment]
process.env.UNI_PLATFORM 可以得到你想要的平台(如mp-weixin, h5 等），然后用条件判断吧。（目前很多根目录的文件都是不支持条件编译的，包括 vite.config.ts， pages.config.ts 等。）

**Comment by KeJunMao** [comment]
> process.env.UNI_PLATFORM 可以得到你想要的平台(如mp-weixin, h5 等），然后用条件判断吧。（目前很多根目录的文件都是不支持条件编译的，包括 vite.config.ts， pages.config.ts 等。）

可以配合这个仓库一起使用~ https://github.com/uni-helper/uni-env
