### ISSUE TITLE
exclude 配置无效

### ISSUE THREAD

**Issue by zaxlct** [uni-helper/vite-plugin-uni-pages#124]
### Describe the bug

```
exclude: ['src/pages/**/components/**/*']
```
配置无效，这么配置有什么问题吗，读了源代码也没问题啊

### Reproduction

怎么改路径都不行

### System Info

```Shell
"@uni-helper/vite-plugin-uni-pages": "^0.2.12",
    macOS
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by KeJunMao** [comment]
相对于 dir, try this

```ts
exclude: ['**/components/**/*.*']
```

**Comment by codercup** [comment]
最小复现仓库，环境 mac pro M1 + pnpm
https://github.com/fly-vue3-templates/vue3-uniapp-template.git

**Comment by codercup** [comment]
> 相对于 dir, try this
> 
> ```ts
> exclude: ['**/components/**/*.*']
> ```

最小复现仓库，环境 mac pro M1 + pnpm
https://github.com/fly-vue3-templates/vue3-uniapp-template.git

**Comment by RJQingHuan** [comment]
exclude不应该写在`pages.config.ts`文件内,应该在`vite.config.ts`

**Comment by RJQingHuan** [comment]
```js
export default defineConfig({
  plugins: [
    UniPages({
      exclude: ['**/components/**/**.*'],
    }),
    uni(),
  ],
})
```

**Comment by codercup** [comment]
> ```js
> export default defineConfig({
>   plugins: [
>     UniPages({
>       exclude: ['**/components/**/**.*'],
>     }),
>     uni(),
>   ],
> })
> ```

原来如此，感谢感谢。

**Comment by codercup** [comment]
希望可以在readme.md里面更新下。

**Comment by OnlyTL** [comment]
我现在在项目根目录下有一个/src/pages/home.vue，我想忽略这个，
我在vite.config.ts中这样配置
```typescript
UniPages({
      exclude: [
        '**/pages/home.vue'
      ]
    }),
```
这样写对吗，为什么还是会在page.json中生成这个页面
