### ISSUE TITLE
pages.config.ts里的exclude配置不生效

### ISSUE THREAD

**Issue by codercup** [uni-helper/vite-plugin-uni-pages#129]
### 描述问题

pages.config.ts里的exclude配置不生效，配置了 `exclude: ['**/components/**/*.*']`，最终pages/xx/components/xx.vue 组件还是会当做页面生成到 pages.json 里面。
配置成 `exclude: ['**/components/**/**.*', '**/components/**.*', 'components']`, 也一样。

**期望 exclude 的配置能生效，并且希望 exclude 默认包含 components.**

### 复现

- 1、pages.config.ts 增加exclude 配置：`exclude: ['**/components/**/*.*']`
- 2、增加vue文件 `pages/index/components/demo.vue`
- 3、`pnpm dev:h5` 运行
- 4、结果 `pages.json` 的pages出现了该页面配置 (希望所有的components下的vue都不会生成为page)
```json
{
    "pages": [
         // others page config,
         {
            "path": "pages/index/components/demo",
            "type": "page"
         }
    ]
 }
```

### 系统信息

```Shell
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 89.36 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v16.20.0/bin/yarn
    npm: 10.2.1 - ~/.nvm/versions/node/v16.20.0/bin/npm
    pnpm: 8.12.1 - ~/.nvm/versions/node/v16.20.0/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 17.1
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
duplicate #124

**Comment by KeJunMao** [comment]
感谢您的反馈，如果你能稳定复现，请提供一个最小复现仓库，谢谢

**Comment by codercup** [comment]
最小复现仓库，环境 mac pro M1 + pnpm
https://github.com/fly-vue3-templates/vue3-uniapp-template.git

**Comment by codercup** [comment]
> 最小复现仓库，环境 mac pro M1 + pnpm https://github.com/fly-vue3-templates/vue3-uniapp-template.git

**Comment by codercup** [comment]
> 感谢您的反馈，如果你能稳定复现，请提供一个最小复现仓库，谢谢

最小复现仓库，环境 mac pro M1 + pnpm
https://github.com/fly-vue3-templates/vue3-uniapp-template.git

**Comment by SunLQuan** [comment]
我也有同样的问题
在pages.config.ts配置了 exclude: ['**/components/**/*.*'],
最终生成pages.config会有	"exclude": [
		"**/components/**/*.*"
	],
但是pages还是会生成上述规则中出现的如下情况

<img width="554" height="273" alt="Image" src="https://github.com/user-attachments/assets/d81edd55-010a-42c2-803e-2029e2ecab04" />

**Comment by skiyee** [comment]
> 我也有同样的问题 在pages.config.ts配置了 exclude: ['**/components/**/_._'], 最终生成pages.config会有 "exclude": [ "**/components/**/_._" ], 但是pages还是会生成上述规则中出现的如下情况
> 
> <img alt="Image" width="554" height="273" src="https://private-user-images.githubusercontent.com/86451190/476244711-d81edd55-010a-42c2-803e-2029e2ecab04.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQ3MDgzODYsIm5iZiI6MTc1NDcwODA4NiwicGF0aCI6Ii84NjQ1MTE5MC80NzYyNDQ3MTEtZDgxZWRkNTUtMDEwYS00MmMyLTgwM2UtMjAyOWUyZWNhYjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODA5VDAyNTQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhYWYyZTI4Zjc1NTRjMzBkZTY1NGQwN2MxZDk3MmQ1YWQ4OTRjMWY4MmU2YmViYzdhYzIyOWJmY2RlMzdjOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sGnKQ1JvyqolFVjnycm6dFPyFBTLU0VTEa8ol6B8IHE">

详见：https://github.com/uni-helper/vite-plugin-uni-pages/issues/124#issuecomment-1876328193
