### ISSUE TITLE
route标签中如何做国际化？

### ISSUE THREAD

**Issue by xiaoshuai9999** [uni-helper/vite-plugin-uni-pages#136]
### 描述问题

这可能不是一个问题，如何使用里面没有说明如何国际化。我使用%%包裹也不行！vue里面国际化是正常的。

### 复现

<route lang="json5" type="home">
{
  style: {
    navigationBarTitleText: '%common.appTitle%'
  }
}
</route>

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 6800H with Radeon Graphics
    Memory: 13.64 GB / 31.19 GB
  Binaries:
    Node: 18.19.0 - ~\AppData\Local\Volta\tools\image\node\18.19.0\node.EXE
    npm: 10.2.3 - ~\AppData\Local\Volta\tools\image\npm\10.2.3\bin\npm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.83)
    Internet Explorer: 11.0.19041.3636
```

### 使用的包管理器

npm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
检查下生成的 pages.json 文件是否符合预期，即有没有包含 `{ style: { navigationBarTitleText: '%common.appTitle%' } }`

**Comment by xiaoshuai9999** [comment]
pages.json: ![image](https://github.com/uni-helper/vite-plugin-uni-pages/assets/74856008/9f498ee4-9bea-4a20-800c-7d7f2769a289) 
![image](https://github.com/uni-helper/vite-plugin-uni-pages/assets/74856008/885e1770-300d-42a8-9397-bc8e9d2917e9)
![image](https://github.com/uni-helper/vite-plugin-uni-pages/assets/74856008/2aa264c2-b123-4be0-968c-724fc28b9288)

**Comment by codercup** [comment]
原字符串输出，并没有替换

**Comment by KeJunMao** [comment]
![image](https://github.com/uni-helper/vite-plugin-uni-pages/assets/18414281/d01abea0-3636-4245-a626-1dc8c1130f6b)

未能复现，检查是否创建了对应语言的 json 文件
