### ISSUE TITLE
homePage可以设置为空或者关闭校验吗

### ISSUE THREAD

**Issue by xiyanglove** [uni-helper/vite-plugin-uni-pages#138]
### 描述问题

因为我们系统路由是动态的，一个项目里面包含了很多项目，每一个项目的homePage都不一样

### 复现

No home page found, check the configuration of pages.config.ts, or add the `homePage` option to UniPages in vite.config.js, or add `type="home"` to the routeBlock of your vue page.

### 系统信息

```Shell
无
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
Closed because no response.
