### ISSUE TITLE
outDir可否传入绝对路径 而不是相对路径

### ISSUE THREAD

**Issue by SimleXin** [uni-helper/vite-plugin-uni-pages#148]
### 对问题的清晰和简明的描述

使用的HX环境开发，ourDir不能传入绝对路径   他会到编译器所在的目录去找pages.json  提示文件找不到
![image](https://github.com/uni-helper/vite-plugin-uni-pages/assets/51394686/9ba7e920-517e-49d9-bdcb-4b50253a9b60)

### 推荐的解决方案

是否可以传入绝对路径？

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by Skiyee** [comment]
该issue应该在已经修复，详见PR: #163

@ModyQyW @Xiphin cc?

**Comment by Xiphin** [comment]
> 该issue应该在已经修复，详见PR: #163
> 
> @ModyQyW @Xiphin cc?

 是的 已经修复

**Comment by ModyQyW** [comment]
请尝试更新 vite-plugin-uni-pages 的版本再运行。
