### ISSUE TITLE
分包可以支持放到 paegs 目录下面

### ISSUE THREAD

**Issue by wukongkong** [uni-helper/vite-plugin-uni-pages#152]
### 对问题的清晰和简明的描述

一般开发习惯分包都是放到 pages 下面，现在放了之后，路径不对，

```
"subPackages": [
    {
      "root": "sub",
      "pages": [
        {
          "path": "../pages/sub/sub-activity/home/index",
          "type": "page",
          "style": {
            "navigationBarTitleText": "我的"
          }
        },
        {
          "path": "../pages/sub/sub-home/demo/index",
          "type": "page",
          "style": {
            "navigationBarTitleText": "分包页面 标题"
          }
        }
      ]
    }
  ]
```

### 推荐的解决方案

支持放到 pages 目录下

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by Skiyee** [comment]
我也遇到这个问题，尝试修复了一下
可以看一下PR，是否符合你的描述

**Comment by wukongkong** [comment]
> 我也遇到这个问题，尝试修复了一下 可以看一下PR，是否符合你的描述

反馈下，现在分包符合要求，但是分包页面也同时会被打入到主包里面，麻烦帮忙看下

**Comment by Skiyee** [comment]
> > 我也遇到这个问题，尝试修复了一下 可以看一下PR，是否符合你的描述
> 
> 反馈下，现在分包符合要求，但是分包页面也同时会被打入到主包里面，麻烦帮忙看下

抱歉，这段时间很忙，目前没有多余的时间去处理相关的issue

欢迎各位朋友们提交相关PR
