### ISSUE TITLE
vloar插件现在没有了vscode里变成了vue official 能支持吗route标签吗

### ISSUE THREAD

**Issue by redwolf1996** [uni-helper/vite-plugin-uni-pages#153]
### 对问题的清晰和简明的描述

vloar插件现在没有了vscode里变成了vue official 能支持吗route标签吗

### 推荐的解决方案

支持最新的vue official

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by Undefined100** [comment]
复议
