### ISSUE TITLE
subPackages下不支持配置插件吗？

### ISSUE THREAD

**Issue by herbieliang** [uni-helper/vite-plugin-uni-pages#160]
### 描述问题

按照uniapp的文档在subPackages下配置使用微信插件，提示“对象字面量只能指定已知属性，并且“plugins”不在类型“SubPackage”中。”，是不支持分包配置插件吗？

### 复现

在subPackages下配置plugins节点

### 系统信息

获取失败报错：RangeError: Invalid count value

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
可以提供一下相关截图和完整复现吗？

**Comment by inoryxun** [comment]
> 可以提供一下相关截图和完整复现吗？

分包的问题能否支持一下呢

**Comment by Skiyee** [comment]
> 分包的问题能否支持一下呢

具体是指哪一方面呢？

> PS: 如果讨论范围与该主题无关，需要重新开启一个 `fix|feat` 的issue

**Comment by gaao** [comment]
> > 分包的问题能否支持一下呢
> 
> 具体是指哪一方面呢？
> 
> > PS: 如果讨论范围与该主题无关，需要重新开启一个 `fix|feat` 的issue

应该是指插件分包的情况，https://developers.weixin.qq.com/miniprogram/dev/framework/plugin/using.html#在分包内引入插件代码包

**Comment by inoryxun** [comment]
> > 分包的问题能否支持一下呢
> 
> 具体是指哪一方面呢？
> 
> > PS: 如果讨论范围与该主题无关，需要重新开启一个 `fix|feat` 的issue
就会分包自动化的问题，比如，咱们插件现在只能自动pages 文件夹下面的vue 吧，如果我想分包，插件会把pages下的所有vue 都自动到主包下面，如此的话我们只能另外独立设置一个文件夹，这时候就无法自动化了

**Comment by Skiyee** [comment]
> 就会分包自动化的问题，比如，咱们插件现在只能自动pages 文件夹下面的vue 吧，如果我想分包，插件会把pages下的所有vue 都自动到主包下面，如此的话我们只能另外独立设置一个文件夹，这时候就无法自动化了

我不太能理解你所描述的问题

你可以重开一个issue？描述也可以呈现的详细一点

**Comment by ModyQyW** [comment]
https://github.com/uni-helper/vite-plugin-uni-pages/commit/4282277bc14b786865419306c9cd12effa172d42

**Comment by breakon** [comment]
> [4282277](https://github.com/uni-helper/vite-plugin-uni-pages/commit/4282277bc14b786865419306c9cd12effa172d42)

请问支持的版本已经发布了吗0.2.27版本没看见

**Comment by SongBana** [comment]
请问哪个版本有呀

**Comment by ModyQyW** [comment]
我的问题，忘合并发布了，对不起各位 @breakon @SongBana
