### ISSUE TITLE
vitest 异常报错：TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by sunpm** [uni-helper/vite-plugin-uni-pages#164]
### 描述问题

使用 vitest 测试时出现一下报错：
![f898d646eb6d9ea734bbf8abdc666f0f](https://github.com/uni-helper/vite-plugin-uni-pages/assets/35005831/2103f01b-2623-4100-ba5c-b751d5df9299)

将 `@uni-helper/vite-plugin-uni-pages`版本回退到`@^0.2.20`就没有这个错误了

### 复现

https://github.com/sunpm/vitesse-uniapp-vue3

### 系统信息

  System:
    OS: macOS 12.6.5
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 387.30 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 9.1.1 - ~/.nvm/versions/node/v18.17.1/bin/pnpm

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
0.2.22
