### ISSUE TITLE
subPackages 配置了目录路径，目录下没文件也会生成分包配置

### ISSUE THREAD

**Issue by sunpm** [uni-helper/vite-plugin-uni-pages#166]
### 对问题的清晰和简明的描述

```js
UniPages({
  subPackages: [
    'src/pages-text',
  ],
})
```
src/pages-text 中并没有文件夹，生成以下配置
```json
"subPackages": [
  {
    "root": "pages-text",
    "pages": []
  },
]
```

`"pages": []` 在开发者工具会报错，其他平台没测试。
可否在 编译这个分包配置至 `pages.json` 之前，如果目录下没页面文件，不生成对应的 `root`

### 推荐的解决方案

我不会🤣

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by Skiyee** [comment]
已修复
