### ISSUE TITLE
uni-page.d.ts 不生效

### ISSUE THREAD

**Issue by yeyuqh** [uni-helper/vite-plugin-uni-pages#171]
### 描述问题

除了按 #140 中所说删除 export 外，在顶部增加 ///<reference types='@dcloudio/types' /> 导入后类型提示可以正常工作。

### 复现

![CleanShot 2024-06-06 at 17 33 02@2x](https://github.com/uni-helper/vite-plugin-uni-pages/assets/49150556/b0ea5bf9-027e-4544-b7ce-825628912ceb)

### 系统信息

1

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
请提供完整复现仓库

**Comment by yeyuqh** [comment]
感谢回复。找到问题所在了，由于某个版本删除了 NavigateToOptions 的 export，导致以前有个文件导入 NavigateToOptions 类型报错，删除这个导入后类型提示正常工作。
