### ISSUE TITLE
创建同名.nvue文件后，page.json会生成两个一样的page，导致冲突

### ISSUE THREAD

**Issue by 0xRainzy** [uni-helper/vite-plugin-uni-pages#174]
### 描述问题

最新版0.2.24还是存在着同样问题

### 复现

![image](https://github.com/uni-helper/vite-plugin-uni-pages/assets/33758668/10e6c001-912e-4fd8-9ed9-f22bb701b0ca)
![image](https://github.com/uni-helper/vite-plugin-uni-pages/assets/33758668/14c79aa7-3a66-4d93-b0be-a64c6ad9472b)

### 系统信息

----------------------------------------------

基础环境信息:
  - os: `Windows 10 10.0.19042`
  - node: `18.19.0`
  - packageManager: `pnpm`

基础依赖信息:
  - vue: `3.4.26`
  - vite: `5.2.8`
  - @dcloudio/uni-app: `3.0.0-4010420240430001`

uni-helper依赖信息:

----------------------------------------------

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by 0xRainzy** [comment]
补充，以上两个页面均在分包下

**Comment by 0xRainzy** [comment]
目前通过配置过滤可以解决该问题
`exclude: ['**/*.nvue']`

**Comment by Skiyee** [comment]
已修复 待review
