### ISSUE TITLE
0.2.25版本生成的pages.json会多一层default

### ISSUE THREAD

**Issue by liamlinyw** [uni-helper/vite-plugin-uni-pages#178]
### 描述问题

生成的pages.json如下, 多了一层default
```
{
  "default": {
    "easycom": {
      ...
    },
    "globalStyle": {
      ...
    },
    "tabBar": {
      ...
    }
  },
  "pages": [
    ...
  ],
  "subPackages": []
}
```

### 复现

-

### 系统信息

-

### 使用的包管理器

npm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Skiyee** [comment]
你好，我未能复现该问题，是否能提供一下最小复现？

**Comment by Skiyee** [comment]
已修复，请升级依赖 `@uni-helper/vite-plugin-uni-pages
` 至 `v0.2.26`
