### ISSUE TITLE
希望提供一个关闭page自动发现的选项

### ISSUE THREAD

**Issue by viarotel** [uni-helper/vite-plugin-uni-pages#49]
### 对问题的清晰和简明的描述

希望提供一个关闭page自动发现的选项

### 推荐的解决方案

希望提供一个关闭page自动发现的选项

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by viarotel** [comment]
自动发现的pages配置与手动配置的pages进行合并时可能会出现合并异常的问题

**Comment by viarotel** [comment]
`
// 临时的解决办法如下
  onAfterScanPages(ctx) {
    console.log('onAfterScanPages.ctx', ctx)
    // Todo
    // 禁用合并自动扫描到的pages
    ctx.pagesPathInfo = []
    return ctx
  }
`

**Comment by viarotel** [comment]
```javascript
      onAfterScanPages(ctx) {
        console.log('onAfterScanPages.ctx', ctx)
        // Todo
        // 禁用合并自动扫描到的pages
        ctx.pagesPathInfo = []
        return ctx
      }
```

**Comment by KeJunMao** [comment]
emmm, 那要是禁用了自动扫描还有用这个插件的必要吗

**Comment by viarotel** [comment]
> emmm, 那要是禁用了自动扫描还有用这个插件的必要吗

当然有必要 js化配置 更方便引入变量动态配置

**Comment by KeJunMao** [comment]
懂了，现在推荐先用 hook 来禁用吧，提议不错

目前项目仓库重构了，见 https://github.com/uni-helper/vite-plugin-uni-pages/pull/48

可能得晚点

**Comment by zguolee** [comment]
https://github.com/uni-helper/vite-plugin-uni-pages/pull/50
