### ISSUE TITLE
release 脚本扫描到了 node_modules 下的 package.json

### ISSUE THREAD

**Issue by KeJunMao** [uni-helper/vite-plugin-uni-pages#59]
### 描述问题

![image](https://user-images.githubusercontent.com/18414281/212504570-f78c2cc9-6dc7-4786-ac68-15f33e3c6991.png)

### 复现

pnpm release

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (6) x64 Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz 
    Memory: 6.16 GB / 15.85 GB
  Binaries:
    Node: 16.19.0 - D:\scoop\apps\pnpm\globalBin\node.EXE
    npm: 8.19.3 - D:\scoop\apps\pnpm\globalBin\npm.CMD   
  Browsers:
    Internet Explorer: 11.0.19041.1566
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by zguolee** [comment]
我没有遇到这个问题，系统是 macOS🥲，可能需要改成 `bumpp packages.json packages/*/package.json`
