### ISSUE TITLE
怎么使用easycom

### ISSUE THREAD

**Issue by transtone** [uni-helper/vite-plugin-uni-pages#78]
### 描述问题

看官网的配置里，easycom组件是写在 pages.conf 文件中的。用了这个组件后，pages.conf变成自动生成的了，那 easycom 相关的配置怎么写呢？

https://github.com/dcloudio/uni-ui#%E4%BD%BF%E7%94%A8-npm--easycom

### 复现

原始示例

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 5.09 GB / 31.86 GB
  Binaries:
    Node: 18.15.0 - D:\bin\nodejs\node.EXE
    Yarn: 1.22.19 - D:\bin\nodejs-bin\yarn.CMD
    npm: 9.6.5 - D:\bin\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (112.0.1722.48)
    Internet Explorer: 11.0.22621.1
```

### 使用的包管理器

npm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by transtone** [comment]
在 pages.config.ts 文件中加上就行。

**Comment by KeJunMao** [comment]
> 在 pages.config.ts 文件中加上就行。

是的，这个库直接接管了 `pages.json`
