### ISSUE TITLE
动态页面怎么使用？

### ISSUE THREAD

**Issue by transtone** [uni-helper/vite-plugin-uni-pages#79]
参考 https://github.com/hannoeru/vite-plugin-pages 的用法，`[id].vue` 命名的页面，会自动生成为动态页面。

但用这样的写法，运行会报错：
![image](https://user-images.githubusercontent.com/46688/235332131-b470c5ad-2b1d-4e66-ac50-25b65548fae4.png)

没有找到相关的文档，开个 issue 问一下。

**Comment by KeJunMao** [comment]
考虑到跨平台，暂不支持

**Comment by transtone** [comment]
那可以和 [uni-simple-router](https://github.com/SilurianYang/uni-simple-router) 结合起来使用吗？

**Comment by KeJunMao** [comment]
可以，这个插件只是接管了pages.json
