### ISSUE TITLE
要如何实现路由拦截的功能？

### ISSUE THREAD

**Issue by terranc** [uni-helper/vite-plugin-uni-pages#84]
### 对问题的清晰和简明的描述

不知道如何才能实现拦截器的功能？

### 推荐的解决方案

在[vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages.git)中可以这么实现：
```
import generatedRoutes from 'virtual:generated-pages'
import { setupLayouts } from 'virtual:generated-layouts'
const routes = setupLayouts(generatedRoutes)

const router = createRouter({
  history: createWebHistory(),
  routes,
  scrollBehavior(to, from, savedPosition) {
    return savedPosition
  },
})
```

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by KeJunMao** [comment]
由于 uni-app 的跨端特性，目前还没有特别好的方案实现路由拦截

现在有一个 WIP 的插件 https://github.com/uni-helper/vite-plugin-uni-middleware 可以实现

**Comment by KeJunMao** [comment]
由于路由拦截与这个插件无关（这个插件仅做了自动扫描并接管 pages.json），可以的话请关闭
