### ISSUE TITLE
pages.config自定义路径

### ISSUE THREAD

**Issue by zh-neng** [uni-helper/vite-plugin-uni-pages#85]
### 对问题的清晰和简明的描述

插件是不是可以自定义配置文件的路径  现在发现pages.config如果引用了其他文件  修改文件不会生效  但是直接修改就可以生效  所以想和其他文件合并 

### 推荐的解决方案

pages.config自定义路径

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by KeJunMao** [comment]
不会生效是什么意思，能提供一个你的 pages.config 吗

**Comment by zguolee** [comment]
> 不会生效是什么意思，能提供一个你的 pages.config 吗

引用外部文件，修改外部文件pages不会热更

**Comment by zh-neng** [comment]
![image](https://github.com/uni-helper/vite-plugin-uni-pages/assets/24434147/48ffafbd-b6d4-4e00-a151-72bf89398dd4)

**Comment by zh-neng** [comment]
我修改了app.config里面的内容时候  不能生效

**Comment by KeJunMao** [comment]
放弃支持此 issue
