### ISSUE TITLE
Volar不生效

### ISSUE THREAD

**Issue by yuanjinkunlou** [uni-helper/vite-plugin-uni-pages#87]
### 描述问题

下载完依赖，重启vscode，在vue文件中还是没有route自定义块的提示

### 复现

![image](https://github.com/uni-helper/vite-plugin-uni-pages/assets/126596599/f62bbefa-3c5c-4d3c-988a-5b8a7d6cf766)
![image](https://github.com/uni-helper/vite-plugin-uni-pages/assets/126596599/4c6101b7-d3a4-47cb-9c9c-21a59a5858b9)

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz    
    Memory: 16.50 GB / 31.83 GB
  Binaries:
    Node: 16.19.1 - ~\AppData\Local\pnpm\node.EXE
    npm: 8.19.3 - ~\AppData\Local\pnpm\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.50)
    Internet Explorer: 11.0.19041.1566
```

### 使用的包管理器

npm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
```html
<route lang="json"></route>
```

这个还是要手动写下的

**Comment by KeJunMao** [comment]
具体的 IntelliSense 需要配合 https://github.com/uni-helper/vite-plugin-uni-pages/tree/main/packages/volar 来使用

**Comment by KeJunMao** [comment]
https://github.com/uni-helper/vitesse-uni-app/blob/main/volar.config.js

参考这个，需要注意的是 volar-service-uni-pages 只支持了 volar 1.7.x+，由于 volar 的版本迭代特别快，改动又特别多 volar-plugins-uni-pages 已被弃用

**Comment by yuanjinkunlou** [comment]
那在<route lang="json"></route>怎么做才能有类型提示呢

**Comment by yuanjinkunlou** [comment]
> ```
> <route lang="json"></route>
> ```
> 
> 这个还是要手动写下的

那在`<route lang="json"></route>`中怎么做才能有类型提示

**Comment by KeJunMao** [comment]
https://github.com/uni-helper/vite-plugin-uni-pages/issues/87#issuecomment-1562468622
