### ISSUE TITLE
插件配置项的回调调用次数问题

### ISSUE THREAD

**Issue by yuanjinkunlou** [uni-helper/vite-plugin-uni-pages#88]
### 描述问题

插件配置项中的回调方法会执行不止一次，这符合常理吗？

### 复现

无

### 系统信息

```Shell
无
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
- vite 启动时会触发一次回调
- 启动时每个页面文件会触发 add而触发回调
- 页面发生改变时也会触发回调

**Comment by KeJunMao** [comment]
try 0.2.4
