### ISSUE TITLE
每次保存，HBX会编译两次

### ISSUE THREAD

**Issue by EvanYung** [uni-helper/vite-plugin-uni-pages#89]
### 描述问题

在vscode上编写，hbx运行到app，每次保存代码hbx会先编译一次，page.json重新生成（即使没有变化），hbx会再次执行编译。

### 复现

保存代码，hbx编译两次

### 系统信息

```Shell
hbx 3.8.4
@uni-helper/vite-plugin-uni-pages 0.2.1
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [x] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
目前是这样的，由于有合并操作，不太好在页面文件改变时提前判断有无改变 route 信息，可以先等一下 #88 的修复
