### ISSUE TITLE
`route`块为空时页面配置不生效

### ISSUE THREAD

**Issue by aboutZZ** [uni-helper/vite-plugin-uni-pages#90]
### 描述问题

在首页`splash.vue`文件中加入`route`块，设置`type="home"`指定为首页
```js
<route type="home" lang="yaml">
</route>
```
项目运行后，首页不是`splash`页面，而是默认值 `pages/index/index`
如果往`route`块中随便写点内容，则配置就生效了: `pages/index/splash`
```js
<route type="home" lang="yaml">
foo:
</route>
```

### 复现

在首页`splash.vue`文件中加入空的`route`块
```js
<route type="home" lang="yaml">
</route>
```

### 系统信息

```Shell
System:                                                 
    OS: Windows 10 10.0.19044                             
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 5.61 GB / 23.84 GB
  Binaries:
    Node: 16.20.0 
    Yarn: 1.22.19
    npm: 8.19.4
  Browsers:
    Firefox: 114.0.1
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
对于 json 来说，这样才是是合法的， 空是合法的吗 yml 吗？
```html
<route type="home" lang="json">
{}
</route>
```

**Comment by aboutZZ** [comment]
我这边建议`content`设个默认值:空的record，函数不要返回`undefined`
https://github.com/uni-helper/vite-plugin-uni-pages/blob/47e3483750e84fe40c98d64555687c930e37e583/packages/core/src/customBlock.ts#L71-L75

当然，如果您认为空route块不合法，那么您可以关闭本issue了

**Comment by zguolee** [comment]
> 我这边建议`content`设个默认值:空的record，函数不要返回`undefined`
> 
> https://github.com/uni-helper/vite-plugin-uni-pages/blob/47e3483750e84fe40c98d64555687c930e37e583/packages/core/src/customBlock.ts#L71-L75
> 
> 当然，如果您认为空route块不合法，那么您可以关闭本issue了

因为之前是参考 vite-plugin-pages，不存在 content 为空且需要 route block 的情况，小程序端需要 route block 上面的一些属性，现在已经被修复。
