### ISSUE TITLE
插件导致热重载失效, 而每次直接刷新页面

### ISSUE THREAD

**Issue by lincenying** [uni-helper/vite-plugin-uni-pages#95]
### 描述问题

![image](https://github.com/uni-helper/vite-plugin-uni-pages/assets/10840991/7cbf11e9-77ef-441a-9d89-f161789b2bff)
![image](https://github.com/uni-helper/vite-plugin-uni-pages/assets/10840991/566b0b25-f43c-4d0e-a1f3-3bf2c6dea773)

图1, 是用了插件, 每次修改代码, 保存后, vite都会发送full-reload给客服端, 导致页面直接刷新, 而不是热重载
图2, 删除了插件后, 恢复正常

### 复现

https://github.com/lincenying/vite-uniapp-vue3

用pnpm安装依赖后,  将 vite.config.ts 里的 UniPages 的相关注释删了

运行服务, 打开F12, 修改src/pages/index.vue, 保存文件, 页面直接刷新

### 系统信息

```Shell
System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 93.11 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    pnpm: 8.6.9 - ~/work/mpapp/chaikaji/node_modules/.bin/pnpm
  Browsers:
    Chrome: 114.0.5735.248
    Safari: 15.5
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
确实是的，啊好烦不知道怎么修

**Comment by lincenying** [comment]
> 确实是的，啊好烦不知道怎么修

我现在是暂时把 `node_modules/vite/dist/client/client.mjs` 里的 `case 'full-reload':` 改成了 `case 'full-reload111':`

需要全刷的时候, 手动刷

**Comment by KeJunMao** [comment]
等我有了好想法我修下
