### ISSUE TITLE
homePage配置

### ISSUE THREAD

**Issue by wen403** [uni-helper/vite-plugin-uni-pages#96]
### 描述问题

为什么写了这个配置还报错而起不生效

### 复现

![image](https://github.com/uni-helper/vite-plugin-uni-pages/assets/67454874/aeba831e-8cd2-47d4-a66a-38a388d7b51f)

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
    Memory: 1.87 GB / 15.92 GB
  Binaries:
    Node: 16.13.0 - D:\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 8.1.0 - D:\nodejs\npm.CMD
    pnpm: 8.0.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.82)
    Internet Explorer: 11.0.19041.1566
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
cc @Ares-Chang

**Comment by KeJunMao** [comment]
先在 `pages/home/index` 使用如下所示看看能不能解决:

```vue
<route type="home" lang="json">
{}
</route>
```

**Comment by lx11573** [comment]
> `homePage` 选项是在 vite.config 里加的
> 
> 也可以在 `pages/home/index` 使用如下解决:
> 
> ```
> <route type="home" lang="json">
> {}
> </route>
> ```
我添加了，也配置了，依然还是有这个问题，不知道什么情况
<img width="1270" alt="image" src="https://github.com/uni-helper/vite-plugin-uni-pages/assets/12030247/acd05192-4fae-4a72-b4e4-f1ab905a8cbc">

**Comment by Ares-Chang** [comment]
你不写它会默认指定 `pages/index` 写了没生效请检查一下包的版本，升级一下。如果依旧有问题请提供一个复现的仓库，感谢。

**Comment by lx11573** [comment]
> 你不写它会默认指定 `pages/index` 写了没生效请检查一下包的版本，升级一下。如果依旧有问题请提供一个复现的仓库，感谢。
包是最新的 0.2.13
[仓库](https://github.com/lx11573/repo.git)

**Comment by Ares-Chang** [comment]
![image](https://github.com/uni-helper/vite-plugin-uni-pages/assets/36911513/feae86f5-356c-4922-9a57-0036b10c15f1)

无子包可以移除对应配置，后继优化一下提示，感谢使用。

**Comment by lx11573** [comment]
> ![image](https://private-user-images.githubusercontent.com/36911513/294192865-feae86f5-356c-4922-9a57-0036b10c15f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzQ1NzcsIm5iZiI6MTcwNDQzNDI3NywicGF0aCI6Ii8zNjkxMTUxMy8yOTQxOTI4NjUtZmVhZTg2ZjUtMzU2Yy00OTIyLTlhNTctMDAzNmIxMGMxNWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA1NTc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNGU2NTFiNjZiNTM4OTZlNjlhMmZmMzk1ZGYyZjJmMTM3NTAwNjE4NmQwZDg1ZTRkYmMzZGQ1M2JmNWUzYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WOM7LrM_YXS_aRN2eXYeKowzu_QpTlurG_0mejYcFMs)
> 
> 无子包可以移除对应配置，后继优化一下提示，感谢使用。

好的，感谢
