### ISSUE TITLE
WARN  (vite-plugin-uni-pages plugin) Sourcemap is likely to be incorrect: a plugin (vite-plugin-uni-pages) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help

### ISSUE THREAD

**Issue by UphkcRNqmafQWcSSSSSS** [uni-helper/vite-plugin-uni-pages#97]
WARN  (vite-plugin-uni-pages plugin) Sourcemap is likely to be incorrect: a plugin (vite-plugin-uni-pages) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help

https://github.com/uni-helper/vite-plugin-uni-pages/blob/07603cd5625c2940978b6a608ff8f0e670718496/packages/core/src/index.ts#L88

```ts
return {
  code: s.toString(),
  map: null,
};
```

**Comment by KeJunMao** [comment]
MagicString 可以输出 sourcemap ，有空我改改

或者你有空发个 PR 吗？

**Comment by KeJunMao** [comment]
请遵守社区 Issue 模板
